version: "3.6"
services:
  docker_node_sc:
    image: dipeshsukhani/ubuntu_npm_git_openzeppelin:v3
    build: .
    ports:
      - "30303:30303"
      - "3000:3000"
      - "4000:4000"
      - "5000:5000"
      - "8080:8080"
      - "8545:8545"
    volumes:
      - .:/home
      - ~/Library/Ethereum:/root/.ethereum
    command: [ "geth", "--syncmode", "light", "--keystore", "/root/.ethereum/keystore", "--port", "30303", "--rpcport", "8546", "--rpc", "--rpccorsdomain", "*", "--nousb" ]
    environment:
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
